# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|  

  # make vm node1 - master
  config.vm.define "node1" do |node|
    node.vm.box = "generic/centos7"
    node.vm.provider "virtualbox" do |vb|
      vb.cpus = 2  
      vb.memory = "4096"      
    end       
    node.vm.box_check_update = false
    node.vm.hostname = "k8s-worker1"
    node.vm.network "public_network", ip: "172.20.10.100"
    node.vm.provision "shell", path: "add-worker-node.sh"   
  end
end
